[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
staking_program = "Dthxpk9KWQ2BDGLhV6G1Seq4dUbGNiDZ5omvgmNMTi4p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
